server:
  port: 8081

spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/identity_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Use 'update' to create the schema on first run. Use 'validate' later.
    show-sql: true

# --- Application Specific Properties ---
app:
  jwt:
    # In production, use a long, random string from a secure vault.
    secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
    expiration-ms: 86400000 # 24 hours